### PR TITLE
Remove 'Clear Variables' button on Peptide and Protein search results grid

### PR DESCRIPTION
**Pull request by labkey-bpatel**
#### Rationale
Clicking on 'Clear Variables' button on Peptide and Protein search results grid is showing underlying parameterized query view.

#### Changes
* Hide 'clear variables' button on Peptide and Protein search results grid

### CODE REVIEW

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
This feels like it's going to be fragile in the face of changes to the HTML or CSS for the grid.

Could we use the `showFilterDescription` property to hide the whole header from the grid? Or are we relying on that header to show what the user searched for? I'm generally OK with relying on the search from section above for that context.

[showFilterDescription](https://www.labkey.org/download/clientapi_docs/javascript-api/symbols/LABKEY.QueryWebPart.html#constructor)

Whatever approach, perhaps we could add test coverage to make sure it's not showing?

**Comment by labkey-bpatel** [comment]
> This feels like it's going to be fragile in the face of changes to the HTML or CSS for the grid.
> 
> Could we use the `showFilterDescription` property to hide the whole header from the grid? Or are we relying on that header to show what the user searched for? I'm generally OK with relying on the search from section above for that context.
> 
> [showFilterDescription](https://www.labkey.org/download/clientapi_docs/javascript-api/symbols/LABKEY.QueryWebPart.html#constructor)
> 
> Whatever approach, perhaps we could add test coverage to make sure it's not showing?

We are relying on `showFilterDescription` to show what user searched for. Test is already updated to test that its not visible.

**Review by labkey-jeckels — APPROVED** [review]
I'm sorry, I don't know how I missed the test updates in my initial review.

They seem to be checking the same potentially fragile CSS class though. Can we also make sure that the "Clear Variables" text from that button isn't showing?

**Comment by labkey-bpatel** [comment]
> I'm sorry, I don't know how I missed the test updates in my initial review.
> 
> They seem to be checking the same potentially fragile CSS class though. Can we also make sure that the "Clear Variables" text from that button isn't showing?

Made a change so that 'Clear Variables' button gets removed instead of hidden, hence the text from that button is not present any longer. Test is updated as well.

**Pull request merged**
